"""empty message

Revision ID: 13376bc15050
Revises: 34e0fdda1b2d
Create Date: 2015-04-30 16:18:19.258214

"""

# revision identifiers, used by Alembic.
revision = '13376bc15050'
down_revision = '34e0fdda1b2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
