"""empty message

Revision ID: 18b1cdee1d7a
Revises: 5a26f06190c1
Create Date: 2015-03-12 18:55:58.066846

"""

# revision identifiers, used by Alembic.
revision = '18b1cdee1d7a'
down_revision = '5a26f06190c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
