"""empty message

Revision ID: 18ec86d5294b
Revises: 245ecc2b05e
Create Date: 2015-04-30 03:43:01.727851

"""

# revision identifiers, used by Alembic.
revision = '18ec86d5294b'
down_revision = '245ecc2b05e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    ### end Alembic commands ###
