"""empty message

Revision ID: 245ecc2b05e
Revises: 234453912b67
Create Date: 2015-04-30 03:40:20.782491

"""

# revision identifiers, used by Alembic.
revision = '245ecc2b05e'
down_revision = '234453912b67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
