"""empty message

Revision ID: 24e7910e3b7
Revises: 54c670353a32
Create Date: 2015-03-11 19:19:30.849147

"""

# revision identifiers, used by Alembic.
revision = '24e7910e3b7'
down_revision = '54c670353a32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
