"""empty message

Revision ID: 291d12725c4b
Revises: 18b1cdee1d7a
Create Date: 2015-04-30 02:59:46.506342

"""

# revision identifiers, used by Alembic.
revision = '291d12725c4b'
down_revision = '18b1cdee1d7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description', sa.String(length=256), nullable=True))
    op.drop_column('event', 'game')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('game', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('event', 'description')
    ### end Alembic commands ###
