"""empty message

Revision ID: 2ec52792bf1b
Revises: 13376bc15050
Create Date: 2015-04-30 16:19:17.908054

"""

# revision identifiers, used by Alembic.
revision = '2ec52792bf1b'
down_revision = '13376bc15050'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
