"""empty message

Revision ID: 33bed37283a5
Revises: 387e3d16ec30
Create Date: 2015-05-03 17:24:02.757718

"""

# revision identifiers, used by Alembic.
revision = '33bed37283a5'
down_revision = '387e3d16ec30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
