"""empty message

Revision ID: 34e0fdda1b2d
Revises: 2ec39838e907
Create Date: 2015-04-30 16:08:11.254722

"""

# revision identifiers, used by Alembic.
revision = '34e0fdda1b2d'
down_revision = '2ec39838e907'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
