"""empty message

Revision ID: 387e3d16ec30
Revises: 9d550454063
Create Date: 2015-05-03 17:19:45.969678

"""

# revision identifiers, used by Alembic.
revision = '387e3d16ec30'
down_revision = '9d550454063'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
