"""empty message

Revision ID: 389f35167c00
Revises: 3a352b5b60ef
Create Date: 2015-04-30 03:30:01.196503

"""

# revision identifiers, used by Alembic.
revision = '389f35167c00'
down_revision = '3a352b5b60ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
