"""empty message

Revision ID: 3a352b5b60ef
Revises: 291d12725c4b
Create Date: 2015-04-30 03:00:18.884323

"""

# revision identifiers, used by Alembic.
revision = '3a352b5b60ef'
down_revision = '291d12725c4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
