"""empty message

Revision ID: 3b492bc6490e
Revises: 2ec52792bf1b
Create Date: 2015-04-30 16:33:51.907433

"""

# revision identifiers, used by Alembic.
revision = '3b492bc6490e'
down_revision = '2ec52792bf1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('user_played')
    op.drop_table('user_hosted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_hosted',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], [u'event.id'], name=u'user_hosted_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'user_hosted_user_id_fkey')
    )
    op.create_table('user_played',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], [u'event.id'], name=u'user_played_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'user_played_user_id_fkey')
    )
    op.drop_table('participants')
    ### end Alembic commands ###
