"""empty message

Revision ID: 4b6628c4d118
Revises: 4f3401e6558
Create Date: 2015-04-30 15:43:19.214527

"""

# revision identifiers, used by Alembic.
revision = '4b6628c4d118'
down_revision = '4f3401e6558'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
