"""empty message

Revision ID: 4c0239c88333
Revises: 380db6119978
Create Date: 2015-05-04 00:57:42.868830

"""

# revision identifiers, used by Alembic.
revision = '4c0239c88333'
down_revision = '380db6119978'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
