"""empty message

Revision ID: 4f3401e6558
Revises: f4a46b829c5
Create Date: 2015-04-30 03:46:36.670514

"""

# revision identifiers, used by Alembic.
revision = '4f3401e6558'
down_revision = 'f4a46b829c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
