"""empty message

Revision ID: 9d550454063
Revises: d5a5a2601ca
Create Date: 2015-05-03 17:01:58.508615

"""

# revision identifiers, used by Alembic.
revision = '9d550454063'
down_revision = 'd5a5a2601ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
