"""empty message

Revision ID: d5a5a2601ca
Revises: 3b492bc6490e
Create Date: 2015-05-03 15:43:05.608295

"""

# revision identifiers, used by Alembic.
revision = 'd5a5a2601ca'
down_revision = '3b492bc6490e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
