"""empty message

Revision ID: f4a46b829c5
Revises: 18ec86d5294b
Create Date: 2015-04-30 03:43:57.925386

"""

# revision identifiers, used by Alembic.
revision = 'f4a46b829c5'
down_revision = '18ec86d5294b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'description')
    ### end Alembic commands ###
